In [4]:
!pip install GraphGT
!pip install dictances
https://openreview.net/pdf?id=nUktmJLz0up

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for dictances: filename=dictances-1.5.6-py3-none-any.whl size=13562 sha256=50e553b501ce5234cb68869675e8b70fa69c8138192835519e795538c26742d7
  Stored in directory: c:\users\cs843\appdata\local\pip\cache\wheels\e5\75\59\4884e0e551a2ebd364e6dda5ad4e0fc85516248ccbd35c0bf4
  Created wheel for support_developer: filename=support_developer-1.0.5-py3-none-any.whl size=5676 sha256=be3bd4feef036cd5c76faaff97daa88a4e022d0b17b584e86bfe849811af7ee4
  Stored in directory: c:\users\cs843\appdata\local\pip\cache\wheels\b6\72\c8\3054a5897ba0713dfa7a941364d68cbd42b0755c8e2ec1c18c
Successfully built dictances support_developer


In [15]:
import graphgt
import dictances 
qm9 = graphgt.DataLoader(name='qm9', save_path='./data', format='numpy')

Found local copy...


In [17]:
input_adj, input_node_feat, input_edge_feat,input_spatial,label= qm9.get_data()


In [46]:
input_node_feat

array([array([[0, 1, 0, 0, 0]]), array([[0, 0, 1, 0, 0]]),
       array([[0, 0, 0, 1, 0]]), ..., array([[0, 1, 0, 0, 0],
                                             [0, 0, 1, 0, 0],
                                             [0, 1, 0, 0, 0],
                                             [0, 1, 0, 0, 0],
                                             [0, 1, 0, 0, 0],
                                             [0, 1, 0, 0, 0],
                                             [0, 1, 0, 0, 0],
                                             [0, 1, 0, 0, 0],
                                             [0, 0, 1, 0, 0]]),
       array([[0, 1, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0]]), array([[0, 1, 0, 0, 0],
                                        [0, 0, 1, 0, 0],
                   

In [45]:
len(label)

133885

In [37]:
qm9.get_data()


(array([array([[0]]), array([[0]]), array([[0]]), ...,
        array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0]]),
        array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0]]),
        array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0

In [30]:
import networkx as nx
nx.from_numpy_matrix(input_adj)

NetworkXError: Input array must be 2D, not 1